@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Dynamic.puml

Container(appMobile, "Aplicativo Móvel","Fornece uma funcionalidade limitada do sistema aos clientes por meio de seus dispositivos móveis.")
ContainerDb(bancoDados, "Banco de Dados", "Esquema de Banco de Dados Relacional", "Armazena informações de registro de usuários, credenciais de autenticação criptografadas, logs de acesso, etc.")
Container_Boundary(apiServiços, "API de Serviços"){
    Component(login, "Controlador de Login", "Controlador Rest Spring MVC", "Permite que os usuários façam login no sistema.")
    Component(seguranca, "Componente de Segurança", "Bean Spring", "Fornece funcionalidades relacionadas ao login, alteração de senhas, etc.")
}

Rel(appMobile, login, "Envia credenciais para", "JSON/HTTPS")
Rel(login, seguranca, "Chama isAuthenticated() em")
Rel(seguranca, bancoDados, "select * from usuarios where username = ?", "JDBC")

@enduml
