@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml

LAYOUT_WITH_LEGEND()

Container(client, "Aplicação Cliente", "Oferece a interface para os clientes solicitarem serviços.")

Container(driver, "Aplicação Prestador", "Oferece a interface para os prestadores aceitarem solicitações de serviços.")

Container(api, "Administrador", "Lida com o gerenciamento de dados e o processamento em tempo real.")

Container_Boundary(database, "Banco de Dados") {
    Component(trips, "Tabela do Banco de Dados", "Armazena informações sobre todos os serviços prestados.")
    Component(drivers, "Tabela de Prestadores", "Tabela do Banco de Dados", "Armazena informações sobre todos os prestadores registrados.")
    Component(clients, "Tabela de Clientes", "Tabela do Banco de Dados", "Armazena informações sobre todos os clientes registrados.")
}

Rel(client, api, "Usa", "JSON/HTTPS")
Rel(driver, api, "Usa", "JSON/HTTPS")

Rel(api, database, "Usa", "Conector de Banco de Dados")

Rel(trips, store, "Envia");
Rel(drivers, store, "Envia");
Rel(clients, store, "Envia");

Rel(routing, trips, "Lê");
Rel(login, clients, "Lê");
Rel(profile, clients, "Lê");

@enduml
