@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml

LAYOUT_WITH_LEGEND()

Person(passageiro, "Cliente", "Usuário do serviço.")

System_Ext(servidorApp, "Servidor do Aplicativo", "Lida com lógica de negócios e comunicação com sistemas externos.")
System_Ext(gatewayPagamento, "Gateway de Pagamento", "Gerencia transações de pagamento.")
System_Ext(rastreamentoVeiculos, "Sistema de Rastreamento de Veículos", "Acompanha a localização dos veículos em tempo real.")

System_Boundary(appTransporte, "Aplicativo de Prestação de serviços") {
    Container(appMobile, "Aplicativo Móvel", "Fornece serviços aos clientes por meio de seus dispositivos móveis.")
    Container(servicoPagamento, "Serviço de Pagamento", "Lida com o processamento de pagamentos.")
    Container(bancoDadosUsuario, "Banco de Dados de Usuários","Armazena informações do usuário, histórico de viagens, etc.")
    Container(servicoAPI, "Serviço de API","Fornece funcionalidade de transporte por meio de uma API RESTful.")
    
    Rel(servicoAPI, servidorApp, "Utiliza", "JSON/HTTPS")
    Rel(servicoAPI, gatewayPagamento, "Processa pagamentos", "HTTPS")
    Rel(servicoAPI, rastreamentoVeiculos, "Obtém localizações de veículos", "HTTPS")
    Rel(appMobile, servicoAPI, "Utiliza", "JSON/HTTPS")
    Rel(appMobile, servicoPagamento, "Utiliza", "JSON/HTTPS")
    Rel(appMobile, bancoDadosUsuario, "Lê e escreve em", "HTTPS")
}

Rel(passageiro, appMobile, "Utiliza", "HTTPS")
Rel(gatewayPagamento, servidorApp, "Processa pagamentos", "HTTPS")
Rel(servidorApp, rastreamentoVeiculos, "Obtém localizações de veículos", "HTTPS")
@enduml
